name: "Fernanda Tosta"
keywords: "marcenaria, projetos"
description: "Busco promover a transformação social através da marcenaria."

url: https://fernandatosta-com.github.io
baseurl: ""
port: 4554
permalink: /:title/

social:
  tumblr: ""
  pinterest: ""
  instagram: "https://www.instagram.com/fernandatosta"
  twitter: "https://twitter.com/nandatosta"
  facebook: ""
  youtube: ""
  vimeo: ""
  github: ""
  soundcloud: ""
  envelope: "mailto:oi@fernandatosta.com"
twitter_user: "nandatosta"

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "list"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# prose.io
prose:
  media: 'media'
  ignore:
    - .gitignore
    - _config.yml
    - _layouts
    - _includes
    - _pages
    - _sass
    - css
    - fonts
    - js
    - CNAME
    - media/favicon
    - media/swipebox
  metadata:
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "nome da página"
      - name: "cover-image"
        field:
          element: "text"
          label: "imagem de capa para a página (tem que ser .jpg por enquanto)"
          placeholder: "horta2.jpg"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md]
