name: "Fernanda Tosta"
keywords: "marcenaria, projetos"
description: "Busco promover a transformação social através da marcenaria."

url: https://fernandatosta.com
baseurl: ""
port: 4554
permalink: /:title/

collections:
  cursos:
    output: true
    permalink: /:collection/:title/
  projetos:
    output: true
    permalink: /:collection/:title/
  conversadeiras:
    output: true
    permalink: /:collection/:title/

social:
  tumblr: ""
  pinterest: ""
  instagram: "https://www.instagram.com/fernandatosta"
  twitter: "https://twitter.com/nandatosta"
  facebook: ""
  youtube-play: "https://www.youtube.com/fernandatosta"
  vimeo: ""
  github: ""
  soundcloud: ""
  envelope: "mailto:oi@fernandatosta.com"
twitter_user: "nandatosta"

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "list"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "cursos"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projetos"
    values:
      layout: "post"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md]

# prose.io
prose:
  media: 'media'
  ignore:
    - .gitignore
    - .sass-cache
    - _config.yml
    - _data
    - _includes
    - _layouts
    - _pages
    - _sass
    - _site
    - CNAME
    - css
    - js
    - media/assets
    - media/covers
    - media/favicon
    - media/swipebox
  metadata:
    _projetos:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "nome do projeto"
      - name: "youtube"
        field:
          element: "text"
          label: "id do video do youtube (só o id)"
          placeholder: "dq9vQD83taU"
      - name: "download"
        field:
          element: "text"
          label: "nome do arquivo do projeto para download"
          placeholder: "/media/projects/adaptacoes-acessiveis/adaptacoes-acessiveis.pdf"
      - name: "cover"
        field:
          element: "text"
          label: "imagem de capa para o projeto (tem que ser .jpg por enquanto)"
          placeholder: "/media/projects/adaptacoes-acessiveis/adaptacoes-acessiveis_00.jpg"
